# Generated by Django 3.1.7 on 2021-06-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('anios', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=10)),
                ('vacunado', models.BooleanField()),
            ],
        ),
    ]
